// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create-team.sql

package db

import (
	"context"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO
  teams(
    team_name,
    manager_id,
    team_members,
    channel_id,
    notification_hour
  )
VALUES
  ($1, $2, $3, $4, $5) RETURNING id
`

type CreateTeamParams struct {
	TeamName         string
	ManagerID        string
	TeamMembers      []string
	ChannelID        string
	NotificationHour uint16
}

func (q *Queries) CreateTeam(ctx context.Context, arg *CreateTeamParams) (uint64, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.TeamName,
		arg.ManagerID,
		arg.TeamMembers,
		arg.ChannelID,
		arg.NotificationHour,
	)
	var id uint64
	err := row.Scan(&id)
	return id, err
}
