// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create-report.sql

package db

import (
	"context"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports(user_id, team_id, report)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateReportParams struct {
	UserID string
	TeamID int64
	Report string
}

func (q *Queries) CreateReport(ctx context.Context, arg *CreateReportParams) (uint64, error) {
	row := q.db.QueryRow(ctx, createReport, arg.UserID, arg.TeamID, arg.Report)
	var id uint64
	err := row.Scan(&id)
	return id, err
}
