// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get-members-to-notify.sql

package db

import (
	"context"
)

const getMembersToNotify = `-- name: GetMembersToNotify :one
SELECT
  ARRAY_AGG(DISTINCT member) :: text[] AS team_members
FROM
  teams,
  UNNEST(team_members) AS member
WHERE
  notification_hour = $1 :: smallint
`

func (q *Queries) GetMembersToNotify(ctx context.Context, notificationHour uint16) ([]string, error) {
	row := q.db.QueryRow(ctx, getMembersToNotify, notificationHour)
	var team_members []string
	err := row.Scan(&team_members)
	return team_members, err
}
