// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Report struct {
	ID        uint64
	UserID    string
	TeamID    int64
	Report    string
	CreatedAt *time.Time
}

type Team struct {
	ID               uint64
	TeamName         string
	ManagerID        string
	TeamMembers      []string
	ChannelID        string
	NotificationHour uint16
}
